### ISSUE TITLE
Process with epid number are excluded

### ISSUE THREAD

**Issue by Arthur111** [mezantrop/sockstat#1]
netstat show pid and epid, when epid is not 0 (the same number as pid) it does not not show up.

netstat -p tcp -v

Theses pids are the ApplePushService (apsd), GeoServices (com.apple.geod)

**Comment by mezantrop** [comment]
Hello @Arthur111, not sure I understood the issue.

**Comment by Arthur111** [comment]
In netstat -p tcp -v there are pid column and epid column.
When epid column is not 0 sockstat does not display the process, ip address, foreign addr etc...

The process ApplePushService and GeoServices are not displayed with sockstat.
netstat -p tcp -v show them.(with the apple ip address).

**Comment by mezantrop** [comment]
Trying to reproduce. How to start these processes with epid, different than 0?

**Comment by Arthur111** [comment]
Weather, Stocks, Xcode did it.
Maybe ApplePushService is iCloud.

**Comment by mezantrop** [comment]
Aha! I have tried xcode, and got trustd running with pid 597 and epid's. Netstat shows them:

![image002](https://github.com/mezantrop/sockstat/assets/21259014/87f0141b-7874-435d-893b-cc67479f6e05)

And sockstat shows them as well:

<img width="963" alt="image001" src="https://github.com/mezantrop/sockstat/assets/21259014/0c45588a-1f83-4b96-becc-dbcfd11ae2c9">

I'm sorry, I still do not see a problem. Can you point out what I miss :)

**Comment by Arthur111** [comment]
Seems we don't have the same environnement.
I am running macos 14.5 on an M2 macbookpro.
sockstat don't display the ip address when there is an epid on netstat.
They appear on netstat with the following application : Weather, Stocks, Xcode.
When i launch Xcode i don't have trustd. (trustd is a deamon to validate website certificate).

**Comment by mezantrop** [comment]
Do you run sockstat from root?

**Comment by Arthur111** [comment]
no, nor  admin.

The pids who do not show up have the same number as the epid and they are not in the lsof command but in the ps command.

**Comment by mezantrop** [comment]
Perhaps, you just see only processes started by your user ID. Unfortunately, sockstat can show all processes only if it's executed by root e.g. sudo sockstat, or setuid bit is set and the file is owned by root.

**Comment by Arthur111** [comment]
netstat is not run by root so sockstat must give the same result.
Write this constraint (run under root) in your doc , readme etc...

**Comment by mezantrop** [comment]
> netstat is not run by root so sockstat must give the same result.

Perhaps, I will solve this in the future.

> Write this constraint (run under root) in your doc , readme etc...

It is written in [README.md](https://github.com/mezantrop/sockstat?tab=readme-ov-file#usage)

**Comment by Arthur111** [comment]
ok thank you

**Comment by mezantrop** [comment]
You are welcome.

**Comment by mezantrop** [comment]
Just a memo for future references, why it's required root privileges. It is true, that netstat doesn't require them, but the idea of sockstat-and-similar-tools is to join information about sockets with users and process details. Unfortunately, it's not possible without getting root. For the same reasons, /bin/ps is setuid root program.

**Comment by Arthur111** [comment]
But it is worse than that.
I compiled [netstat](https://opensource.apple.com/source/network_cmds/network_cmds-328/netstat.tproj/) from apple source. 

There is nothing about pid, epid and no "-v" option (who give pid and epid).
So you must be root to access pid and epid from proc_pidinfo function or use their secret version of netstat.

Steve Jobs called that "mumbo jumbo".
